# Generated by Django 4.1.1 on 2022-09-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_rename_keywords_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
