# Generated by Django 4.1.1 on 2022-09-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_service_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('headline', models.CharField(blank=True, max_length=250, null=True)),
                ('tags', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('promoted', models.BooleanField(default=False)),
                ('rating', models.FloatField(max_length=5)),
                ('description', models.TextField(max_length=2500)),
                ('avatar', models.ImageField(blank=True, default='static_media/user.png', upload_to='agent/avatars')),
                ('category', models.ManyToManyField(to='about.subcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
