# Generated by Django 4.1.1 on 2022-09-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_agent_delete_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='rating',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
    ]
