# Generated by Django 4.1.1 on 2022-09-25 12:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_agent_collab_agent_found_agent_headquarters_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'services'},
        ),
        migrations.AddField(
            model_name='agent',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
