# Generated by Django 4.1.1 on 2022-09-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_alter_subcategory_options_agent_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='pricing',
            name='price1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricing',
            name='price2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricing',
            name='price3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricing',
            name='features',
            field=models.ManyToManyField(to='about.feature'),
        ),
    ]
