# Generated by Django 4.1.1 on 2022-09-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0020_state_priority_alter_plan_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='min_project_size',
            field=models.CharField(blank=True, choices=[('5000', '5k'), ('10000', '10k'), ('50000', '50k'), ('100000', '100k'), ('500000', '500k'), ('1000000', '1m'), ('5000000', '5m'), ('10000000', '10m'), ('50000000', '50m'), ('100000000', '100m')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='team',
            field=models.CharField(blank=True, choices=[('1 - 3', 'Less than 4'), ('4 - 10', '4 to 10'), ('11 - 49', '11 to 49'), ('50 - 100', '50 to 100'), ('100 - 500', '100 to 500'), ('500+', 'Over 500')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='priority',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
