# Generated by Django 4.1.1 on 2022-09-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0021_agent_min_project_size_alter_agent_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='headline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
