# Generated by Django 4.1.1 on 2022-10-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0024_alter_agent_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='headline',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=7500)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('', '')], max_length=250)),
                ('rating', models.FloatField(blank=True, max_length=5, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.agent')),
            ],
        ),
    ]
