# Generated by Django 4.1.1 on 2022-11-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0028_alter_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='position',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
